require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - vendor/**/*
    - node_modules/**/*
    - bin/*
    - db/schema.rb

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb

Style/ClassAndModuleChildren:
  Enabled: false
